# This is the main configuration file for your Netlify site.

[build]
  functions = "netlify/functions"

# Rule for individual EVENT pages
[[redirects]]
  from = "/event/*"
  to = "/.netlify/functions/get-event-details?slug=:splat"
  status = 200

# Rule for individual VENUE pages
[[redirects]]
  from = "/venue/*"
  to = "/.netlify/functions/get-venue-details?slug=:splat"
  status = 200

# Rule for the main EVENTS listing page
[[redirects]]
  from = "/events"
  to = "/events.html"
  status = 200

# Rule for the main VENUES listing page
[[redirects]]
  from = "/all-venues"
  to = "/all-venues.html"
  status = 200

# Rule for the COMMUNITY page
[[redirects]]
  from = "/community"
  to = "/community.html"
  status = 200

# Rule for the GET LISTED form page
[[redirects]]
  from = "/get-listed"
  to = "/get-listed.html"
  status = 200
  
# --- NEW: Admin Section Rules ---

# Directs users to the login page
[[redirects]]
    from = "/admin"
    to = "/admin-login.html"
    status = 200
    
[[redirects]]
    from = "/admin/login"
    to = "/admin-login.html"
    status = 200
    
# Rule for the hidden admin migration tool
[[redirects]]
    from = "/admin/migrate"
    to = "/admin-migrate.html"
    status = 200
    
# Rule for the hidden admin settings page
[[redirects]]
    from = "/admin/settings"
    to = "/admin-settings.html"
    status = 200
