# This is the main configuration file for your Netlify site.

# Specifies build settings for Netlify
[build]
  # Directory that contains the deploy-ready HTML files and assets.
  publish = "/"

# Specifies how serverless functions are handled
[functions]
  # Main directory for all serverless functions
  directory = "netlify/functions/"


# --- Page Redirect and Rewrite Rules ---

# Rule for individual EVENT pages
[[redirects]]
  from = "/event/*"
  to = "/.netlify/functions/get-event-details?slug=:splat"
  status = 200

# Rule for individual VENUE pages
[[redirects]]
  from = "/venue/*"
  to = "/.netlify/functions/get-venue-details?slug=:splat"
  status = 200

# Rule for the main EVENTS listing page
[[redirects]]
  from = "/events"
  to = "/events.html"
  status = 200

# Rule for the main VENUES listing page
[[redirects]]
  from = "/all-venues"
  to = "/all-venues.html"
  status = 200

# Rule for the COMMUNITY page
[[redirects]]
  from = "/community"
  to = "/community.html"
  status = 200

# Rule for the CONTACT page
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

# Rule for the GET LISTED form page
[[redirects]]
  from = "/get-listed"
  to = "/get-listed.html"
  status = 200
  
# Rule for the Public Promoter Tools Page
[[redirects]]
    from = "/promoter-tool"
    to = "/promoter-tool.html"
    status = 200

# --- Admin Section Rules ---

# Directs users to the login page
[[redirects]]
    from = "/admin"
    to = "/admin-login.html"
    status = 200
    
[[redirects]]
    from = "/admin/login"
    to = "/admin-login.html"
    status = 200
    
# Rule for the hidden admin settings page
[[redirects]]
    from = "/admin/settings"
    to = "/admin-settings.html"
    status = 200

# Rule for the Pending Approvals page
[[redirects]]
    from = "/admin/approvals"
    to = "/admin-approvals.html"
    status = 200

# Rule for the Add Venue admin tool
[[redirects]]
    from = "/admin/add-venue"
    to = "/admin-add-venue.html"
    status = 200

# Rule for the Edit Approved Events admin tool
[[redirects]]
    from = "/admin/edit-events"
    to = "/admin-edit-events.html"
    status = 200

# Rule for the dynamic sitemap
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true
