# This is the main configuration file for your Netlify site.

[build]
  functions = "netlify/functions"

# Rule for individual EVENT pages
[[redirects]]
  from = "/event/*"
  to = "/.netlify/functions/get-event-details?slug=:splat"
  status = 200

# NEW Rule for individual VENUE pages
[[redirects]]
  from = "/venue/*"
  to = "/.netlify/functions/get-venue-details?slug=:splat"
  status = 200
