# This is the main configuration file for your Netlify site.

[build]
  functions = "netlify/functions"

# Rule for individual EVENT pages
[[redirects]]
  from = "/event/*"
  to = "/.netlify/functions/get-event-details?slug=:splat"
  status = 200

# Rule for individual VENUE pages
[[redirects]]
  from = "/venue/*"
  to = "/.netlify/functions/get-venue-details?slug=:splat"
  status = 200

# Rule for the COMMUNITY page
[[redirects]]
  from = "/community"
  to = "/community.html"
  status = 200

# Rule for the VENUES listing form page
[[redirects]]
  from = "/venues"
  to = "/venues.html"
  status = 200
